/**
 * Pluto
 * The API for Pluto
 *
 * OpenAPI spec version: 1.0
 * Contact: support@pluto.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Account } from './Account';
import { AccountAllOfBusinessProfile } from './AccountAllOfBusinessProfile';
import { AccountAllOfIntegrations } from './AccountAllOfIntegrations';
import { AccountAllOfSettings } from './AccountAllOfSettings';
import { AccountAllOfTeam } from './AccountAllOfTeam';
import { PayoutWallet } from './PayoutWallet';
import { HttpFile } from '../http/http';

export class AccountAllOf {
    'parent_account'?: string | Account;
    'connected_accounts'?: Array<string>;
    'platform_account': boolean;
    'application_fee_percent': number;
    'team'?: Array<AccountAllOfTeam>;
    'verified'?: boolean;
    'business_profile'?: AccountAllOfBusinessProfile;
    'settings'?: AccountAllOfSettings;
    'integrations'?: AccountAllOfIntegrations;
    'payout_wallets'?: Array<PayoutWallet>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "parent_account",
            "baseName": "parent_account",
            "type": "string | Account",
            "format": ""
        },
        {
            "name": "connected_accounts",
            "baseName": "connected_accounts",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "platform_account",
            "baseName": "platform_account",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "application_fee_percent",
            "baseName": "application_fee_percent",
            "type": "number",
            "format": ""
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "Array<AccountAllOfTeam>",
            "format": ""
        },
        {
            "name": "verified",
            "baseName": "verified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "business_profile",
            "baseName": "business_profile",
            "type": "AccountAllOfBusinessProfile",
            "format": ""
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "AccountAllOfSettings",
            "format": ""
        },
        {
            "name": "integrations",
            "baseName": "integrations",
            "type": "AccountAllOfIntegrations",
            "format": ""
        },
        {
            "name": "payout_wallets",
            "baseName": "payout_wallets",
            "type": "Array<PayoutWallet>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountAllOf.attributeTypeMap;
    }

    public constructor() {
    }
}

