/**
 * Pluto
 * The API for Pluto
 *
 * OpenAPI spec version: 1.0
 * Contact: support@pluto.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AccountAllOfSettingsPayments {
    'invoice_prefix'?: string;
    'invoice_reminder_frequency'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "invoice_prefix",
            "baseName": "invoice_prefix",
            "type": "string",
            "format": ""
        },
        {
            "name": "invoice_reminder_frequency",
            "baseName": "invoice_reminder_frequency",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountAllOfSettingsPayments.attributeTypeMap;
    }

    public constructor() {
    }
}

