/**
 * Pluto
 * The API for Pluto
 *
 * OpenAPI spec version: 1.0
 * Contact: support@pluto.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AccountsIdSettings {
    'retry_period_duration'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "retry_period_duration",
            "baseName": "retry_period_duration",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountsIdSettings.attributeTypeMap;
    }

    public constructor() {
    }
}

