/**
 * Prism
 * The API for Prism
 *
 * OpenAPI spec version: 1.0
 * Contact: support@prism.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountBranding } from './AccountBranding';
import { PayoutWallet } from './PayoutWallet';
import { HttpFile } from '../http/http';

export class Account {
    'branding'?: AccountBranding;
    'connectedAccounts'?: Array<any>;
    'created'?: Date;
    'ethWallet'?: PayoutWallet;
    'id'?: string;
    'invoicePrefix'?: string;
    'name': string;
    'parentAccount'?: any;
    'platformAccount'?: boolean;
    'solWallet'?: PayoutWallet;
    'test'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "branding",
            "baseName": "branding",
            "type": "AccountBranding",
            "format": ""
        },
        {
            "name": "connectedAccounts",
            "baseName": "connected_accounts",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "ethWallet",
            "baseName": "eth_wallet",
            "type": "PayoutWallet",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "invoicePrefix",
            "baseName": "invoice_prefix",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentAccount",
            "baseName": "parent_account",
            "type": "any",
            "format": ""
        },
        {
            "name": "platformAccount",
            "baseName": "platform_account",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "solWallet",
            "baseName": "sol_wallet",
            "type": "PayoutWallet",
            "format": ""
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Account.attributeTypeMap;
    }

    public constructor() {
    }
}

