/**
 * Pluto
 * The API for Pluto
 *
 * OpenAPI spec version: 1.0
 * Contact: support@pluto.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Account } from './Account';
import { AccountAllOfBranding } from './AccountAllOfBranding';
import { AccountAllOfSettings } from './AccountAllOfSettings';
import { AccountAllOfTeam } from './AccountAllOfTeam';
import { PayoutWallet } from './PayoutWallet';
import { HttpFile } from '../http/http';

export class AccountAllOf {
    'application_fee_percent': number;
    'branding'?: AccountAllOfBranding;
    'connected_accounts'?: Array<Account>;
    'invoice_prefix'?: string;
    'name': string;
    'parent_account'?: string | Account;
    'payout_wallets'?: Array<PayoutWallet>;
    'platform_account': boolean;
    'settings'?: AccountAllOfSettings;
    'team'?: Array<AccountAllOfTeam>;
    'verified'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "application_fee_percent",
            "baseName": "application_fee_percent",
            "type": "number",
            "format": ""
        },
        {
            "name": "branding",
            "baseName": "branding",
            "type": "AccountAllOfBranding",
            "format": ""
        },
        {
            "name": "connected_accounts",
            "baseName": "connected_accounts",
            "type": "Array<Account>",
            "format": ""
        },
        {
            "name": "invoice_prefix",
            "baseName": "invoice_prefix",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "parent_account",
            "baseName": "parent_account",
            "type": "string | Account",
            "format": ""
        },
        {
            "name": "payout_wallets",
            "baseName": "payout_wallets",
            "type": "Array<PayoutWallet>",
            "format": ""
        },
        {
            "name": "platform_account",
            "baseName": "platform_account",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "AccountAllOfSettings",
            "format": ""
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "Array<AccountAllOfTeam>",
            "format": ""
        },
        {
            "name": "verified",
            "baseName": "verified",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountAllOf.attributeTypeMap;
    }

    public constructor() {
    }
}

