/**
 * Pluto
 * The API for Pluto
 *
 * OpenAPI spec version: 1.0
 * Contact: support@pluto.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountAllOfBusinessProfileLinks } from './AccountAllOfBusinessProfileLinks';
import { AccountAllOfBusinessProfileSupport } from './AccountAllOfBusinessProfileSupport';
import { HttpFile } from '../http/http';

export class AccountAllOfBusinessProfile {
    'name'?: string;
    'business_description'?: string;
    'support'?: AccountAllOfBusinessProfileSupport;
    'links'?: AccountAllOfBusinessProfileLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "business_description",
            "baseName": "business_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "support",
            "baseName": "support",
            "type": "AccountAllOfBusinessProfileSupport",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "AccountAllOfBusinessProfileLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountAllOfBusinessProfile.attributeTypeMap;
    }

    public constructor() {
    }
}

