/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiKeyType } from './ApiKeyType';
import { HttpFile } from '../http/http';

export class ApiKeyCreateRequest {
    'account'?: string;
    'name'?: string;
    'note'?: string;
    'type'?: ApiKeyType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "account",
            "baseName": "account",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ApiKeyType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiKeyCreateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

