/**
 * Pluto
 * The API for Pluto
 *
 * OpenAPI spec version: 1.0
 * Contact: support@pluto.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Account } from './Account';
import { ApiKeyAllOf } from './ApiKeyAllOf';
import { Model } from './Model';
import { HttpFile } from '../http/http';

export class ApiKey {
    'id': string;
    'created': Date;
    'object': string;
    'test': boolean;
    'account': string | Account;
    'name'?: string;
    'note'?: string;
    'key': ApiKeyKeyEnum;
    'type': ApiKeyTypeEnum;
    'last_used'?: Date;
    'admin': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string | Account",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "ApiKeyKeyEnum",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ApiKeyTypeEnum",
            "format": ""
        },
        {
            "name": "last_used",
            "baseName": "last_used",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "admin",
            "baseName": "admin",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiKey.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ApiKeyKeyEnum = "publishable" | "secret" | "restricted" ;
export type ApiKeyTypeEnum = "publishable" | "secret" | "restricted" ;

