/**
 * Prism
 * The API for Prism
 *
 * OpenAPI spec version: 1.0
 * Contact: support@prism.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PricesBasePrice } from './PricesBasePrice';
import { HttpFile } from '../http/http';

export class CreatePriceBody {
    'amount'?: string;
    'base_price'?: PricesBasePrice;
    'chain': string;
    'currency': string;
    'metadata'?: any;
    'product': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "base_price",
            "baseName": "base_price",
            "type": "PricesBasePrice",
            "format": ""
        },
        {
            "name": "chain",
            "baseName": "chain",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreatePriceBody.attributeTypeMap;
    }

    public constructor() {
    }
}

