/**
 * Pluto
 * The API for Pluto
 *
 * OpenAPI spec version: 1.0
 * Contact: support@pluto.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Account } from './Account';
import { CustomerAllOf } from './CustomerAllOf';
import { CustomersIdBillingDetails } from './CustomersIdBillingDetails';
import { Model } from './Model';
import { PaymentIntent } from './PaymentIntent';
import { Wallet } from './Wallet';
import { HttpFile } from '../http/http';

export class Customer {
    'created': Date;
    'id': string;
    'object': string;
    'test': boolean;
    'account': string | Account;
    'billing_details'?: CustomersIdBillingDetails;
    'email'?: string;
    'last_payment': string | PaymentIntent;
    'name'?: string;
    'payments': Array<PaymentIntent>;
    'phone'?: string;
    'wallets': Array<Wallet>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string | Account",
            "format": ""
        },
        {
            "name": "billing_details",
            "baseName": "billing_details",
            "type": "CustomersIdBillingDetails",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "last_payment",
            "baseName": "last_payment",
            "type": "string | PaymentIntent",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "payments",
            "baseName": "payments",
            "type": "Array<PaymentIntent>",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "wallets",
            "baseName": "wallets",
            "type": "Array<Wallet>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Customer.attributeTypeMap;
    }

    public constructor() {
    }
}

