/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CustomAmount {
    '_default': number;
    'maximum': number;
    'minimum': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "_default",
            "baseName": "default",
            "type": "number",
            "format": "double"
        },
        {
            "name": "maximum",
            "baseName": "maximum",
            "type": "number",
            "format": "double"
        },
        {
            "name": "minimum",
            "baseName": "minimum",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return CustomAmount.attributeTypeMap;
    }

    public constructor() {
    }
}

