/**
 * Pluto
 * The API for Pluto
 *
 * OpenAPI spec version: 1.0
 * Contact: support@pluto.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Account } from './Account';
import { CustomerAllOfBillingDetails } from './CustomerAllOfBillingDetails';
import { PaymentIntent } from './PaymentIntent';
import { Wallet } from './Wallet';
import { HttpFile } from '../http/http';

export class CustomerAllOf {
    'account': string | Account;
    'name'?: string;
    'email'?: string;
    'phone'?: string;
    'billing_details'?: CustomerAllOfBillingDetails;
    'wallets': Array<Wallet>;
    'payments': Array<PaymentIntent>;
    'last_payment': PaymentIntent;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "account",
            "baseName": "account",
            "type": "string | Account",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "billing_details",
            "baseName": "billing_details",
            "type": "CustomerAllOfBillingDetails",
            "format": ""
        },
        {
            "name": "wallets",
            "baseName": "wallets",
            "type": "Array<Wallet>",
            "format": ""
        },
        {
            "name": "payments",
            "baseName": "payments",
            "type": "Array<PaymentIntent>",
            "format": ""
        },
        {
            "name": "last_payment",
            "baseName": "last_payment",
            "type": "PaymentIntent",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerAllOf.attributeTypeMap;
    }

    public constructor() {
    }
}

