/**
 * Prism
 * The API for Prism
 *
 * OpenAPI spec version: 1.0
 * Contact: support@prism.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerBillingDetails } from './CustomerBillingDetails';
import { HttpFile } from '../http/http';

export class Customer {
  'id': string;
  'account'?: string;
  'billingDetails'?: CustomerBillingDetails;
  'created': Date;
  'email'?: string;
  'name'?: string;
  'phone'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'id',
      baseName: '_id',
      type: 'string',
      format: '',
    },
    {
      name: 'account',
      baseName: 'account',
      type: 'string',
      format: '',
    },
    {
      name: 'billingDetails',
      baseName: 'billing_details',
      type: 'CustomerBillingDetails',
      format: '',
    },
    {
      name: 'created',
      baseName: 'created',
      type: 'Date',
      format: 'date-time',
    },
    {
      name: 'email',
      baseName: 'email',
      type: 'string',
      format: '',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
      format: '',
    },
    {
      name: 'phone',
      baseName: 'phone',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return Customer.attributeTypeMap;
  }

  public constructor() {}
}
