/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from './Address';
import { HttpFile } from '../http/http';

export class IBusinessProfile {
    'name': string;
    'product_description'?: string;
    'url'?: string;
    'support_url'?: string;
    'support_email'?: string;
    'support_phone'?: string;
    'support_address'?: Address;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "product_description",
            "baseName": "product_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "support_url",
            "baseName": "support_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "support_email",
            "baseName": "support_email",
            "type": "string",
            "format": ""
        },
        {
            "name": "support_phone",
            "baseName": "support_phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "support_address",
            "baseName": "support_address",
            "type": "Address",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IBusinessProfile.attributeTypeMap;
    }

    public constructor() {
    }
}

