/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Chain } from './Chain';
import { CouponDuration } from './CouponDuration';
import { Currency } from './Currency';
import { HttpFile } from '../http/http';

export class ICoupon {
    'id': string;
    'object': string;
    'created': number;
    'test': boolean;
    'account': string;
    'name': string;
    'code': string;
    'amount_off': number;
    'percent_off': number;
    'currency'?: Currency;
    'chain'?: Chain;
    'duration': CouponDuration;
    'duration_in_days'?: number;
    'max_redemptions'?: number;
    'times_redeemed': number;
    'redeem_by'?: Date | number;
    'archived': boolean;
    'valid': boolean;
    'products': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number",
            "format": "double"
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount_off",
            "baseName": "amount_off",
            "type": "number",
            "format": "double"
        },
        {
            "name": "percent_off",
            "baseName": "percent_off",
            "type": "number",
            "format": "double"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "Currency",
            "format": ""
        },
        {
            "name": "chain",
            "baseName": "chain",
            "type": "Chain",
            "format": ""
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "CouponDuration",
            "format": ""
        },
        {
            "name": "duration_in_days",
            "baseName": "duration_in_days",
            "type": "number",
            "format": "double"
        },
        {
            "name": "max_redemptions",
            "baseName": "max_redemptions",
            "type": "number",
            "format": "double"
        },
        {
            "name": "times_redeemed",
            "baseName": "times_redeemed",
            "type": "number",
            "format": "double"
        },
        {
            "name": "redeem_by",
            "baseName": "redeem_by",
            "type": "Date | number",
            "format": ""
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "valid",
            "baseName": "valid",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ICoupon.attributeTypeMap;
    }

    public constructor() {
    }
}

