/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ICustomerBillingDetails } from './ICustomerBillingDetails';
import { IPaymentIntent } from './IPaymentIntent';
import { IWallet } from './IWallet';
import { HttpFile } from '../http/http';

export class ICustomer {
    'id': string;
    'object': string;
    'created': number;
    'test': boolean;
    'account': string;
    'name'?: string;
    'email'?: string;
    'phone'?: string;
    'wallets': Array<IWallet>;
    'payments'?: number;
    'last_payment'?: IPaymentIntent;
    'billing_details': ICustomerBillingDetails;
    'metadata': { [key: string]: any; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number",
            "format": "double"
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "wallets",
            "baseName": "wallets",
            "type": "Array<IWallet>",
            "format": ""
        },
        {
            "name": "payments",
            "baseName": "payments",
            "type": "number",
            "format": "double"
        },
        {
            "name": "last_payment",
            "baseName": "last_payment",
            "type": "IPaymentIntent",
            "format": ""
        },
        {
            "name": "billing_details",
            "baseName": "billing_details",
            "type": "ICustomerBillingDetails",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: any; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ICustomer.attributeTypeMap;
    }

    public constructor() {
    }
}

