/**
 * Pluto
 * The API for Pluto
 *
 * OpenAPI spec version: 1.0
 * Contact: support@pluto.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse400Error } from './InlineResponse400Error';
import { HttpFile } from '../http/http';

export class InlineResponse400 {
    'error'?: InlineResponse400Error;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "InlineResponse400Error",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse400.attributeTypeMap;
    }

    public constructor() {
    }
}

