/**
 * Prism
 * The API for Prism
 *
 * OpenAPI spec version: 1.0
 * Contact: support@prism.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InlineObject1 {
  'description'?: string;
  'invoice': string;
  'percent': number;
  'wallet': string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'description',
      baseName: 'description',
      type: 'string',
      format: '',
    },
    {
      name: 'invoice',
      baseName: 'invoice',
      type: 'string',
      format: '',
    },
    {
      name: 'percent',
      baseName: 'percent',
      type: 'number',
      format: '',
    },
    {
      name: 'wallet',
      baseName: 'wallet',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InlineObject1.attributeTypeMap;
  }

  public constructor() {}
}
