/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InvoiceStatus } from './InvoiceStatus';
import { HttpFile } from '../http/http';

export class InvoiceUpdateRequest {
    'metadata'?: { [key: string]: any; };
    'due'?: Date | number;
    'notify'?: boolean;
    'status'?: InvoiceStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "due",
            "baseName": "due",
            "type": "Date | number",
            "format": ""
        },
        {
            "name": "notify",
            "baseName": "notify",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "InvoiceStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InvoiceUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

