/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LineItem } from './LineItem';
import { HttpFile } from '../http/http';

export class InvoiceCreateRequest {
    'customer'?: string;
    'metadata'?: { [key: string]: any; };
    'price'?: string;
    'coupon'?: string;
    'line_items'?: Array<LineItem>;
    'trial_period_days'?: number;
    'due'?: Date | number;
    'notify'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customer",
            "baseName": "customer",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string",
            "format": ""
        },
        {
            "name": "coupon",
            "baseName": "coupon",
            "type": "string",
            "format": ""
        },
        {
            "name": "line_items",
            "baseName": "line_items",
            "type": "Array<LineItem>",
            "format": ""
        },
        {
            "name": "trial_period_days",
            "baseName": "trial_period_days",
            "type": "number",
            "format": "double"
        },
        {
            "name": "due",
            "baseName": "due",
            "type": "Date | number",
            "format": ""
        },
        {
            "name": "notify",
            "baseName": "notify",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InvoiceCreateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

