/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IBilling } from './IBilling';
import { IBranding } from './IBranding';
import { IPayments } from './IPayments';
import { HttpFile } from '../http/http';

export class ISettings {
    'billing': IBilling;
    'branding': IBranding;
    'payments': IPayments;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "billing",
            "baseName": "billing",
            "type": "IBilling",
            "format": ""
        },
        {
            "name": "branding",
            "baseName": "branding",
            "type": "IBranding",
            "format": ""
        },
        {
            "name": "payments",
            "baseName": "payments",
            "type": "IPayments",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ISettings.attributeTypeMap;
    }

    public constructor() {
    }
}

