/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IInvoice } from './IInvoice';
import { LineItem } from './LineItem';
import { SubscriptionStatus } from './SubscriptionStatus';
import { HttpFile } from '../http/http';

export class ISubscription {
    'id': string;
    'object': string;
    'created': number;
    'test': boolean;
    'account': string;
    'platform_account'?: string;
    'price': string;
    'line_items': Array<LineItem>;
    'trial_period_days': number;
    'customer': string;
    'status': SubscriptionStatus;
    'current_period_start': Date | number;
    'current_period_end': Date | number;
    'cancel_at_period_end': boolean;
    'pause_collection': boolean;
    'cancel_at'?: Date | number;
    'canceled_at'?: Date | number;
    'latest_invoice': IInvoice;
    'metadata': { [key: string]: any; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number",
            "format": "double"
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string",
            "format": ""
        },
        {
            "name": "platform_account",
            "baseName": "platform_account",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string",
            "format": ""
        },
        {
            "name": "line_items",
            "baseName": "line_items",
            "type": "Array<LineItem>",
            "format": ""
        },
        {
            "name": "trial_period_days",
            "baseName": "trial_period_days",
            "type": "number",
            "format": "double"
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SubscriptionStatus",
            "format": ""
        },
        {
            "name": "current_period_start",
            "baseName": "current_period_start",
            "type": "Date | number",
            "format": ""
        },
        {
            "name": "current_period_end",
            "baseName": "current_period_end",
            "type": "Date | number",
            "format": ""
        },
        {
            "name": "cancel_at_period_end",
            "baseName": "cancel_at_period_end",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "pause_collection",
            "baseName": "pause_collection",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "cancel_at",
            "baseName": "cancel_at",
            "type": "Date | number",
            "format": ""
        },
        {
            "name": "canceled_at",
            "baseName": "canceled_at",
            "type": "Date | number",
            "format": ""
        },
        {
            "name": "latest_invoice",
            "baseName": "latest_invoice",
            "type": "IInvoice",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: any; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ISubscription.attributeTypeMap;
    }

    public constructor() {
    }
}

