/**
 * Pluto
 * The API for Pluto
 *
 * OpenAPI spec version: 1.0
 * Contact: support@pluto.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Price } from './Price';
import { HttpFile } from '../http/http';

export class PaymentIntentAllOfLineItems {
    'price'?: any | Price;
    'price_data'?: any;
    'quantity'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "price",
            "baseName": "price",
            "type": "any | Price",
            "format": ""
        },
        {
            "name": "price_data",
            "baseName": "price_data",
            "type": "any",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentIntentAllOfLineItems.attributeTypeMap;
    }

    public constructor() {
    }
}

