/**
 * Pluto
 * The API for Pluto
 *
 * OpenAPI spec version: 1.0
 * Contact: support@pluto.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Account } from './Account';
import { LineItem } from './LineItem';
import { Model } from './Model';
import { PaymentLinkAllOf } from './PaymentLinkAllOf';
import { PaymentLinkAllOfAfterCompletion } from './PaymentLinkAllOfAfterCompletion';
import { HttpFile } from '../http/http';

export class PaymentLink {
    'id': string;
    'created': Date;
    'object': string;
    'test': boolean;
    'account'?: string | Account;
    'platform_account'?: string | Account;
    'active'?: boolean;
    'after_completion'?: PaymentLinkAllOfAfterCompletion;
    'line_items'?: Array<LineItem>;
    'currency': PaymentLinkCurrencyEnum;
    'chain': PaymentLinkChainEnum;
    'expires_at'?: Date;
    'max_usages'?: number;
    'remaining_stock'?: number;
    'application_fee_percent'?: number;
    'url'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string | Account",
            "format": ""
        },
        {
            "name": "platform_account",
            "baseName": "platform_account",
            "type": "string | Account",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "after_completion",
            "baseName": "after_completion",
            "type": "PaymentLinkAllOfAfterCompletion",
            "format": ""
        },
        {
            "name": "line_items",
            "baseName": "line_items",
            "type": "Array<LineItem>",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "PaymentLinkCurrencyEnum",
            "format": ""
        },
        {
            "name": "chain",
            "baseName": "chain",
            "type": "PaymentLinkChainEnum",
            "format": ""
        },
        {
            "name": "expires_at",
            "baseName": "expires_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "max_usages",
            "baseName": "max_usages",
            "type": "number",
            "format": ""
        },
        {
            "name": "remaining_stock",
            "baseName": "remaining_stock",
            "type": "number",
            "format": ""
        },
        {
            "name": "application_fee_percent",
            "baseName": "application_fee_percent",
            "type": "number",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaymentLink.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PaymentLinkCurrencyEnum = "eth" | "sol" ;
export type PaymentLinkChainEnum = "eth" | "sol" ;

