/**
 * Prism
 * The API for Prism
 *
 * OpenAPI spec version: 1.0
 * Contact: support@prism.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Account } from './Account';
import { Price } from './Price';
import { HttpFile } from '../http/http';

export class ProductAllOf {
    'account': string | Account;
    'description'?: string;
    'name': string;
    'prices'?: Array<Price>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "account",
            "baseName": "account",
            "type": "string | Account",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "prices",
            "baseName": "prices",
            "type": "Array<Price>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductAllOf.attributeTypeMap;
    }

    public constructor() {
    }
}

