/**
 * Prism
 * The API for Prism
 *
 * OpenAPI spec version: 1.0
 * Contact: support@prism.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Account } from './Account';
import { Customer } from './Customer';
import { Invoice } from './Invoice';
import { Payment } from './Payment';
import { Price } from './Price';
import { SubscriptionPeriod } from './SubscriptionPeriod';
import { HttpFile } from '../http/http';

export class SubscriptionAllOf {
    'account': string | Account;
    'platform_account'?: string | Account;
    'price': string | Price;
    'customer': string | Customer;
    'next_invoice'?: Invoice;
    'status': SubscriptionAllOfStatusEnum;
    'pause_collection': boolean;
    'cancel_at'?: number;
    'canceled_at'?: number;
    'invoices'?: Array<Invoice>;
    'payments'?: Array<Payment>;
    'current_period'?: SubscriptionPeriod;
    'latest_period'?: SubscriptionPeriod;
    'periods'?: Array<SubscriptionPeriod>;
    'trial_period_duration'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "account",
            "baseName": "account",
            "type": "string | Account",
            "format": ""
        },
        {
            "name": "platform_account",
            "baseName": "platform_account",
            "type": "string | Account",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string | Price",
            "format": ""
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "string | Customer",
            "format": ""
        },
        {
            "name": "next_invoice",
            "baseName": "next_invoice",
            "type": "Invoice",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SubscriptionAllOfStatusEnum",
            "format": ""
        },
        {
            "name": "pause_collection",
            "baseName": "pause_collection",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "cancel_at",
            "baseName": "cancel_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "canceled_at",
            "baseName": "canceled_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "invoices",
            "baseName": "invoices",
            "type": "Array<Invoice>",
            "format": ""
        },
        {
            "name": "payments",
            "baseName": "payments",
            "type": "Array<Payment>",
            "format": ""
        },
        {
            "name": "current_period",
            "baseName": "current_period",
            "type": "SubscriptionPeriod",
            "format": ""
        },
        {
            "name": "latest_period",
            "baseName": "latest_period",
            "type": "SubscriptionPeriod",
            "format": ""
        },
        {
            "name": "periods",
            "baseName": "periods",
            "type": "Array<SubscriptionPeriod>",
            "format": ""
        },
        {
            "name": "trial_period_duration",
            "baseName": "trial_period_duration",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionAllOf.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SubscriptionAllOfStatusEnum = "active" | "canceled" | "trialing" | "past_due" ;

