/**
 * Prism
 * The API for Prism
 *
 * OpenAPI spec version: 1.0
 * Contact: support@prism.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Account } from './Account';
import { Customer } from './Customer';
import { Invoice } from './Invoice';
import { Model } from './Model';
import { Payment } from './Payment';
import { Price } from './Price';
import { SubscriptionAllOf } from './SubscriptionAllOf';
import { SubscriptionAllOfLineItems } from './SubscriptionAllOfLineItems';
import { HttpFile } from '../http/http';

export class Subscription {
    'created': Date;
    'id': string;
    'object': string;
    'test': boolean;
    'account': string | Account;
    'canceled_at'?: number;
    'current_period_end': number;
    'current_period_start': number;
    'customer': string | Customer;
    'invoices'?: Array<Invoice>;
    'latest_invoice'?: Invoice;
    'line_items'?: SubscriptionAllOfLineItems;
    'pause_collection': boolean;
    'payments'?: Array<Payment>;
    'platform_account'?: string | Account;
    'price': string | Price;
    'status': SubscriptionStatusEnum;
    'trial_period_duration'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "created",
            "baseName": "created",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string | Account",
            "format": ""
        },
        {
            "name": "canceled_at",
            "baseName": "canceled_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "current_period_end",
            "baseName": "current_period_end",
            "type": "number",
            "format": ""
        },
        {
            "name": "current_period_start",
            "baseName": "current_period_start",
            "type": "number",
            "format": ""
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "string | Customer",
            "format": ""
        },
        {
            "name": "invoices",
            "baseName": "invoices",
            "type": "Array<Invoice>",
            "format": ""
        },
        {
            "name": "latest_invoice",
            "baseName": "latest_invoice",
            "type": "Invoice",
            "format": ""
        },
        {
            "name": "line_items",
            "baseName": "line_items",
            "type": "SubscriptionAllOfLineItems",
            "format": ""
        },
        {
            "name": "pause_collection",
            "baseName": "pause_collection",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "payments",
            "baseName": "payments",
            "type": "Array<Payment>",
            "format": ""
        },
        {
            "name": "platform_account",
            "baseName": "platform_account",
            "type": "string | Account",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "string | Price",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SubscriptionStatusEnum",
            "format": ""
        },
        {
            "name": "trial_period_duration",
            "baseName": "trial_period_duration",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Subscription.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SubscriptionStatusEnum = "active" | "canceled" | "trialing" | "past_due" ;

