/**
 * Prism
 * The API for Prism
 *
 * OpenAPI spec version: 1.0
 * Contact: support@prism.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountsBranding } from './AccountsBranding';
import { HttpFile } from '../http/http';

export class UpdateAccountBody {
    'branding'?: AccountsBranding;
    'invoice_prefix'?: string;
    'name'?: string;
    'platform_account'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "branding",
            "baseName": "branding",
            "type": "AccountsBranding",
            "format": ""
        },
        {
            "name": "invoice_prefix",
            "baseName": "invoice_prefix",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "platform_account",
            "baseName": "platform_account",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateAccountBody.attributeTypeMap;
    }

    public constructor() {
    }
}

